#!/usr/bin/env php
<?php
define('LARAVEL_START', microtime(true));

require __DIR__.'/Vendor/autoload.php';

$app = \App\App::App();

$app->singleton(Illuminate\Contracts\Console\Kernel::class, App\Console::class);
$app->singleton(Illuminate\Contracts\Debug\ExceptionHandler::class, App\Handler::class);

$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

$status = $kernel->handle($input = new Symfony\Component\Console\Input\ArgvInput, new Symfony\Component\Console\Output\ConsoleOutput);
$kernel->terminate($input, $status);

exit($status);
